server:
  port: 8090
  
spring:
  application:
    name: PostService

  profiles:
    active: ${SPRING_ACTIVE_PROFILE:development}

  jpa:
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  datasource:
    hikari:
      connection-test-query: SELECT 1
      minimum-idle: 1
      maximum-pool-size: 5
      pool-name: dbcp1
    url: ${DB_URL:jdbc:mysql://localhost:3306/springjpa_db?allowPublicKeyRetrieval=true&useSSL=false}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}
    initialization-mode: ALWAYS
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver